#include <jni.h>
#include <stdint.h>
#include <stdlib.h>

// Generated by: javac -h native OceanMonumentCoords.java
#include "OceanMonumentCoords_CubiomesSupport_CubiomesHandle.h"

// Cubiomes public API
#include "generator.h"
#include "finders.h"

// Native handle stored as jlong on the Java side
typedef struct CubiomesHandle {
    Generator g;
    int mc;
} CubiomesHandle;

// Map Java enum ordinal -> cubiomes MC_* constant
static int map_mc_version(int ordinal) {
    switch (ordinal) {
        case 0: return MC_1_18;
        case 1: return MC_1_19;
        case 2: return MC_1_20;
        case 3: return MC_1_21;
        default: return MC_1_18;
    }
}

JNIEXPORT jlong JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1create
  (JNIEnv *env, jclass cls, jlong seed, jint mcVersionOrdinal)
{
    (void)env; (void)cls;

    CubiomesHandle *h = (CubiomesHandle*)calloc(1, sizeof(CubiomesHandle));
    if (!h) return 0;

    h->mc = map_mc_version((int)mcVersionOrdinal);

    // Initialize generator (returns void in modern cubiomes)
    setupGenerator(&h->g, h->mc, 0);

    // Seed overworld
    applySeed(&h->g, DIM_OVERWORLD, (int64_t)seed);

    return (jlong)(uintptr_t)h;
}

JNIEXPORT jint JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1isViableMonument
  (JNIEnv *env, jclass cls, jlong handle, jint chunkX, jint chunkZ)
{
    (void)env; (void)cls;

    if (handle == 0) return 0;
    CubiomesHandle *h = (CubiomesHandle*)(uintptr_t)handle;

    // Convert CHUNK -> BLOCK coordinates (required by cubiomes)
    int bx = ((int)chunkX) << 4;
    int bz = ((int)chunkZ) << 4;

    int ok = isViableStructurePos(Monument, &h->g, bx, bz, 0);
    return ok ? 1 : 0;
}

// Batch viability check to avoid millions of JNI calls
JNIEXPORT void JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1isViableMonumentBatch
  (JNIEnv *env, jclass cls, jlong handle, jintArray chunkXs, jintArray chunkZs, jbyteArray outFlags)
{
    (void)cls;

    if (handle == 0) return;
    if (chunkXs == NULL || chunkZs == NULL || outFlags == NULL) return;

    CubiomesHandle *h = (CubiomesHandle*)(uintptr_t)handle;

    jsize nX = (*env)->GetArrayLength(env, chunkXs);
    jsize nZ = (*env)->GetArrayLength(env, chunkZs);
    jsize nO = (*env)->GetArrayLength(env, outFlags);

    jsize n = nX;
    if (nZ < n) n = nZ;
    if (nO < n) n = nO;
    if (n <= 0) return;

    jboolean isCopyX = JNI_FALSE;
    jboolean isCopyZ = JNI_FALSE;
    jboolean isCopyO = JNI_FALSE;

    jint *xs = (*env)->GetIntArrayElements(env, chunkXs, &isCopyX);
    jint *zs = (*env)->GetIntArrayElements(env, chunkZs, &isCopyZ);
    jbyte *out = (*env)->GetByteArrayElements(env, outFlags, &isCopyO);

    if (xs == NULL || zs == NULL || out == NULL) {
        if (xs) (*env)->ReleaseIntArrayElements(env, chunkXs, xs, JNI_ABORT);
        if (zs) (*env)->ReleaseIntArrayElements(env, chunkZs, zs, JNI_ABORT);
        if (out) (*env)->ReleaseByteArrayElements(env, outFlags, out, 0);
        return;
    }

    for (jsize i = 0; i < n; i++) {
        int bx = ((int)xs[i]) << 4;
        int bz = ((int)zs[i]) << 4;
        int ok = isViableStructurePos(Monument, &h->g, bx, bz, 0);
        out[i] = (jbyte)(ok ? 1 : 0);
    }

    (*env)->ReleaseIntArrayElements(env, chunkXs, xs, JNI_ABORT);
    (*env)->ReleaseIntArrayElements(env, chunkZs, zs, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, outFlags, out, 0);
}

JNIEXPORT void JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1free
  (JNIEnv *env, jclass cls, jlong handle)
{
    (void)env; (void)cls;

    if (handle == 0) return;
    CubiomesHandle *h = (CubiomesHandle*)(uintptr_t)handle;
    free(h);
}