/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OceanMonumentCoords_CubiomesSupport_CubiomesHandle */

#ifndef _Included_OceanMonumentCoords_CubiomesSupport_CubiomesHandle
#define _Included_OceanMonumentCoords_CubiomesSupport_CubiomesHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OceanMonumentCoords_CubiomesSupport_CubiomesHandle
 * Method:    c_create
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1create
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     OceanMonumentCoords_CubiomesSupport_CubiomesHandle
 * Method:    c_isViableMonument
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1isViableMonument
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     OceanMonumentCoords_CubiomesSupport_CubiomesHandle
 * Method:    c_isViableMonumentBatch
 * Signature: (J[I[I[B)V
 */
JNIEXPORT void JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1isViableMonumentBatch
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jbyteArray);

/*
 * Class:     OceanMonumentCoords_CubiomesSupport_CubiomesHandle
 * Method:    c_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OceanMonumentCoords_00024CubiomesSupport_00024CubiomesHandle_c_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
